# Generated by Django 5.0.2 on 2025-02-03 18:36

import dineapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantname', models.TextField(default='*')),
                ('productname', models.TextField(default='*')),
                ('username', models.TextField(default='*')),
                ('productprice', models.FloatField()),
                ('productimage', models.TextField(default='*')),
                ('quantity', models.IntegerField(default=1)),
                ('extradetails', models.TextField(default='*')),
                ('status', models.TextField(default='new')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('cbid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='*')),
                ('query', models.TextField(default='*')),
                ('response', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestFeedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantid', models.TextField(default='*')),
                ('restaurantname', models.TextField(default='*')),
                ('feedback', models.TextField(default='*')),
                ('emotion', models.TextField(default='*')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestGallery',
            fields=[
                ('galleryid', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantid', models.TextField(default='*')),
                ('restaurantname', models.TextField(default='*')),
                ('title', models.TextField(default='*')),
                ('baseimg', models.TextField(default='*')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestSale',
            fields=[
                ('saleid', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantid', models.TextField(default='*')),
                ('restaurantname', models.TextField(default='*')),
                ('startdate', models.TextField(default='*')),
                ('enddate', models.TextField(default='*')),
                ('status', models.TextField(default='*')),
                ('title', models.TextField(default='*')),
                ('description', models.TextField(default='*')),
                ('baseimg', models.TextField(default='*')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(default=dineapp.models.generate_transaction_id, max_length=10, unique=True)),
                ('restaurantname', models.TextField(default='*')),
                ('customername', models.CharField(max_length=255)),
                ('custmoreid', models.TextField(default='*')),
                ('dishdetails', models.TextField(default='*')),
                ('gotcreditscore', models.TextField(default='*')),
                ('billamount', models.FloatField()),
                ('discountamount', models.FloatField(default=0.0)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCreditsData',
            fields=[
                ('ccid', models.AutoField(primary_key=True, serialize=False)),
                ('creditscore', models.FloatField(default=0.0)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='******', max_length=255)),
                ('contact', models.CharField(default='1111111111', max_length=20)),
                ('email', models.EmailField(default='project1878@gmail.com', max_length=254, unique=True)),
                ('baseimg', models.TextField(default='*')),
                ('address', models.TextField(default='*')),
                ('latitude', models.TextField(default='*')),
                ('longitude', models.TextField(default='*')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Restaurant Name', max_length=255)),
                ('address', models.CharField(default='Address', max_length=255)),
                ('contact', models.CharField(default='Contact Number', max_length=20)),
                ('email', models.EmailField(default='project1878@gmail.com', max_length=254)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.TextField(default='*')),
                ('longitude', models.TextField(default='*')),
                ('baseimg', models.TextField(default='*')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('metadata', models.TextField(default='*')),
                ('price', models.FloatField()),
                ('image', models.TextField(default='*')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dineapp.restaurant')),
            ],
        ),
    ]
