# Generated by Django 5.2.14 on 2026-05-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Camera', max_length=100)),
                ('source_type', models.CharField(choices=[('video_file', 'Video File'), ('webcam', 'Webcam'), ('rtsp', 'RTSP Stream')], default='video_file', max_length=20)),
                ('source_path', models.TextField(default='')),
                ('static_frame', models.TextField(default='*')),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='dineapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableZone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(default='Table 1', max_length=50)),
                ('polygon_coords', models.JSONField(default=list)),
                ('capacity', models.IntegerField(default=4)),
                ('cooldown_seconds', models.IntegerField(default=300)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cooldown', 'Cooldown')], default='available', max_length=20)),
                ('person_count', models.IntegerField(default=0)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#00e676', max_length=7)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='dineapp.camerafeed')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_zones', to='dineapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('avg_occupancy_pct', models.FloatField(default=0.0)),
                ('total_tables', models.IntegerField(default=0)),
                ('avg_occupied_tables', models.FloatField(default=0.0)),
                ('avg_turnover_minutes', models.FloatField(default=0.0)),
                ('peak_person_count', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_analytics', to='dineapp.restaurant')),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('restaurant', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='OccupancySnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('person_count', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dineapp.tablezone')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['zone', '-timestamp'], name='dineapp_occ_zone_id_d94249_idx'), models.Index(fields=['-timestamp'], name='dineapp_occ_timesta_20c1ab_idx')],
            },
        ),
    ]
